# Generated by Django 5.1.4 on 2024-12-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_remove_broadcast_completed_broadcast_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='target_users',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='total_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='total_successful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='total_target_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BroadcastTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='broadcast.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='broadcast.user')),
            ],
        ),
    ]
