# Generated by Django 5.1.4 on 2024-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_remove_broadcast_target_users_broadcast_total_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='users',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
