# Generated by Django 5.1.4 on 2025-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_broadcast_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='buttons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=20),
        ),
    ]
